# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kevin's blog
fullname: Kevin Yan
email: kevin.yan@mail.utoronto.ca
description: > # this means to ignore newlines until "baseurl:"
 Hi, this is a blog that documents some of the cool things that I have learned
 and would like to document for myself, as well as share with others.
baseurl: "" # the subpath of your site, e.g. /blog
url: "127.0.0.1:4000" # the base hostname & protocol for your site
twitter_username: k_yan88
github_username:  yankev
highlighter: pygments

# Build settings
markdown: kramdown
